### ISSUE TITLE
Videos quit playing

### ISSUE THREAD

**Issue by darklurker69** [homolaradek/plugin.video.mazacka#1]
Hi Homola.  Earlier this week, the Mazacka add-on quit showing the video stream in Kodi.  The add-on will load with no problem, but when I select one of the streams to watch, it shows the spinning cursor for a few seconds, then does nothing.  I know the Mazacka cam is working because I can see it on the Mall.TV site with a web browser, but it will not show in the Kodi add-in.

I am running Kodi 18.8 on an Amazon Firestick 4k, and have the add-on at version 1.2.0.  

Also, thank you for this plugin.  Watching Prague from the back of the mazacka is my favorite reason to use the Firestick.  Thank you greatly for your efforts.

**Comment by homolaradek** [comment]
Hello Darklurker, many thanks for reporting this issue, I really appreciate it.
Yesterday I fixed it. Update has been already published, so please verify that your addon is updated to version 1.2.1.
Glad to see that someone enjoys virtual travelling through our beloved city. Hope you'll be able to visit Prague soon when this Covid thing will be over. Stay safe and thank you once again!

**Comment by darklurker69** [comment]
Thank You Homola.  Yes, it is working again.  I hope one day to visit
Prague - it is a beautiful and old city, and the Mazacka tram shows it to
the world.

Thanks again, and stay safe.
Dave
